[package]
name = "paystack-rs"
version = "0.1.0"
edition = "2021"
authors = ["Oghenemarho Orukele <orukele.dev@gmail.com>"]


[dependencies]
thiserror = "1"
serde_json = "1"
reqwest = { version = "0.11", features = ["json"] }
tokio = { version = "1", features = ["full"] }
serde = {version ="1", features = ["derive"]}

[dev-dependencies]
fake = "2"
rand = "0.8"